name: AUR Sync

on:
  push:
    branches:
      - main

jobs:
  aur-sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Publish to AUR
        uses: KSXPCK/setup-makepkg@v1

      - name: Update .SRCINFO and Push to AUR
        run: |
          # Setup SSH
          mkdir -p ~/.ssh
          echo "${{ secrets.AUR_SSH_PRIVATE_KEY }}" > ~/.ssh/id_aur
          chmod 600 ~/.ssh/id_aur
          ssh-keyscan aur.archlinux.org >> ~/.ssh/known_hosts
          
          # Configure Git
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          
          # Clone AUR repo
          GIT_SSH_COMMAND="ssh -i ~/.ssh/id_aur" git clone ssh://aur@aur.archlinux.org/lazychad-git.git aur-repo
          
          # Copy files from GitHub to AUR folder
          cp PKGBUILD aur-repo/
          cp lazychad.install aur-repo/
          
          # Update .SRCINFO inside the AUR folder
          cd aur-repo
          makepkg --printsrcinfo > .SRCINFO
          
          # Commit and Push
          git add PKGBUILD .SRCINFO lazychad.install
          if git diff --staged --quiet; then
            echo "No changes to commit"
          else
            git commit -m "bot: sync from github [${{ github.sha }}]"
            GIT_SSH_COMMAND="ssh -i ~/.ssh/id_aur" git push origin master
          fi
